### PR TITLE
Update Report

### PR DESCRIPTION
**Pull request by christian-bromann**
I hope it is ok to suggest a slight change to the final comparison. I am maintainer of WebdriverIO and can prove that it can run tests on all browser as well as on mobile devices. I even ran automation tests on SmartTV using this framework.

In addition to that: you can surely disable CSP by using one of the chrome plugins available for that or maybe directly via CDP.

### CODE REVIEW

**Review by bootstraponline — APPROVED** [review]

**Comment by bootstraponline** [comment]
Awesome. Thanks for the pull request!

Do you know if WebdriverIO has plans for playwright support if a company were willing to provide a development team to work on this?

**Comment by christian-bromann** [comment]
> Do you know if WebdriverIO has plans for playwright support if a company were willing to provide a development team to work on this?

We would love such contribution. The reason why we currently don't have Playwright support is because we don't want to have users download 3 browser binaries every time they download WebdriverIO. However I think it would be very interesting to support Playwright as automation backend.

**Comment by bootstraponline** [comment]
Thanks for the feedback. I will see if there's enough interest internally to invest in this area.

**Comment by bootstraponline** [comment]
@christian-bromann If we added Playwright as an automation backend to WebdriverIO, could we run Playwright tests on Sauce Lab's headless product? The challenge for us with Playwright is the lack of cloud vendor support and no sync API. If WebdriverIO solves both, that would be compelling.

**Comment by christian-bromann** [comment]
> could we run Playwright tests on Sauce Lab's headless product?

No you couldn't. Playwright requires custom browser that are provided by the Playwright module. In order to allow automation on Firefox and Safari the team has patched these browser to provide you that patched version. This means that you actually don't test on a real Firefox or Safari using Puppeteer. While many people say the areas they have patched are around automation and not related to the browsers rendering engine it still at the end is not an actual browser that is used by your customers.

> If WebdriverIO solves both, that would be compelling.

Can you please elaborate on where WebdriverIO is currently falling short? I hear a lot that WebDriver is slow which I disagree with because if you run tests in parallel you can keep any test suite run within minutes. I am aware the there is a lack in the ability to control the network actions which we will address in webdriverio/webdriverio#5336. Note that these features will work for local testing as well as on Sauce Labs. Is there anything else that you see in Playwright but not supported in WebdriverIO?

**Comment by bootstraponline** [comment]
> No you couldn't.

That's true today. I talked with Sauce Labs and it sounds like in the future this might be possible.

>  hear a lot that WebDriver is slow which I disagree with because if you run tests in parallel you can keep any test suite run within minutes.

Appium had similar challenges. There's a performance and capabilities gap compared with more browser native automation technologies. Parallel execution is cool and it's even better when the framework itself is super fast.

**Pull request merged**
